name: tinkok
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  gap: ^3.0.1
  google_fonts: ^6.1.0
  dartz: ^0.10.1
  quiver: ^3.2.1
  bloc_hooks: 
    git:
      url: https://github.com/evaqum/bloc_hooks.git
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  go_router_builder: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Tinkok
      fonts:
        - asset: assets/fonts/Tinkok.ttf
