name: tinkok
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  gap: ^3.0.1
  google_fonts: ^6.1.0
  bloc_hooks: 
    git:
      url: https://github.com/evaqum/bloc_hooks.git
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl: ^0.19.0
  provider: ^6.1.1
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  go_router_builder: ^2.4.0
  mocktail: ^1.0.2
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Tinkok
      fonts:
        - asset: assets/fonts/Tinkok.ttf
