version: '3'
  
tasks:
  codegen:once:
    aliases:
      - codegen:o
      - co
    summary: Run build_runner
    cmd: dart run build_runner --delete-conflicting-outputs
    
  codegen:watch:
    aliases:
      - codegen:w
      - cw
    summary: Run build_runner (watch mode)
    cmd: dart run build_runner watch --delete-conflicting-outputs

  build:apk:
    summary: Build apk
    cmd: flutter build apk
