/// Flutter icons Tinkok
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tinkok
///      fonts:
///       - asset: fonts/Tinkok.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Tinkok {
  Tinkok._();

  static const _kFontFam = 'Tinkok';
  static const String? _kFontPkg = null;

  static const IconData crown = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruble = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
